name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: main
      id: main
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: main
        setup-command: git clone https://github.com/nrevutska-students/react-web-workers-test
          tests && npm install
        command: CI=true npm test
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN_RESULTS: "${{steps.main.outputs.result}}"
      with:
        runners: main
